### PR TITLE
Update import path

### PR DESCRIPTION
**Pull request by abhinav**
Changes the import path of the repository
to match its new home at github.com/pulumi/go-change.

### CODE REVIEW

**Comment by abhinav** [comment]
image

fixing changelog bot

**Comment by abhinav** [comment]
I have a PR pending on changelog-bot to fix this.

**Comment by abhinav** [comment]
Fix to changelog bot deployed.

**Review by AaronFriel — APPROVED** [review]

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
🤨  I don't think bors works here anymore.

**Comment by AaronFriel** [comment]
Did we fire bors? :(

**Comment by AaronFriel** [comment]
bors merge

**Comment by abhinav** [comment]
bors retry

**Comment by abhinav** [comment]
goreleaser replacements are deprecated

**Comment by abhinav** [comment]
bors merge

**Comment by abhinav** [comment]
bors merge

**Pull request merged**
